const dayjs = require("dayjs")

// Relative Time
const relativeTime = require('dayjs/plugin/relativeTime')
dayjs.extend(relativeTime)
console.log(dayjs("20111031", "YYYYMMDD").fromNow())
console.log(dayjs("20120620", "YYYYMMDD").fromNow())
console.log(dayjs().startOf('day').fromNow())
console.log(dayjs().endOf('day').fromNow())
console.log(dayjs().startOf('hour').fromNow())
// Calendar Time
const calendar = require('dayjs/plugin/calendar')
dayjs.extend(calendar)
console.log(dayjs().subtract(10, 'days').calendar())
console.log(dayjs().subtract(6, 'days').calendar())
console.log(dayjs().subtract(3, 'days').calendar())
console.log(dayjs().subtract(1, 'days').calendar())
console.log(dayjs().calendar())
console.log(dayjs().add(1, 'days').calendar())
console.log(dayjs().add(3, 'days').calendar())
console.log(dayjs().add(10, 'days').calendar())
// Multiple Locale Support
const localizedFormat = require('dayjs/plugin/localizedFormat')
dayjs.extend(localizedFormat)
console.log(dayjs.locale())
console.log(dayjs().format('LT'))
console.log(dayjs().format('LTS'))
console.log(dayjs().format('L'))
console.log(dayjs().format('l'))
console.log(dayjs().format('LL'))
console.log(dayjs().format('ll'))
console.log(dayjs().format('LLL'))
console.log(dayjs().format('lll'))
console.log(dayjs().format('LLLL'))
console.log(dayjs().format('llll'))